# Generated by Django 6.0.4 on 2026-04-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='created_at_gte_deadline',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('deadline__isnull', True), models.Q(('deadline__isnull', False), ('created_at__gte', models.F('deadline'))), _connector='OR'), name='created_at_gte_deadline'),
        ),
    ]
