# Generated by Django 6.0.4 on 2026-04-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_remove_task_created_at_gte_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='created_at_gte_deadline',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('deadline__isnull', False), ('created_at__lte', models.F('deadline'))), name='created_at_lte_deadline'),
        ),
    ]
